"""empty message

Revision ID: af1a92fee8d5
Revises: 
Create Date: 2022-07-26 20:39:01.493378

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af1a92fee8d5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment__like', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'comment__like', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'comment__like', type_='foreignkey')
    op.drop_column('comment__like', 'user_id')
    # ### end Alembic commands ###
