"""empty message

Revision ID: b2711bff029c
Revises: 99e1e06b4a05
Create Date: 2022-07-23 20:06:36.895145

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2711bff029c'
down_revision = '99e1e06b4a05'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('last_connection', sa.String(length=120), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_connection')
    # ### end Alembic commands ###
